### ISSUE TITLE
What are the support functions in epluspar?

### ISSUE THREAD

**Issue by mdakyen** [hongyuanjia/epluspar#25]
Good day Hongyuanjia,
please I need help with functions in epluspar. 
If
**choice_space** is used to specify optimization parameter of character type 
**float_space** is used to specify optimization parameter of float type in a sequential manner
**integer_space**is used to specify optimization parameter of integer type in a sequential manner
what functions can I use to specify float and integer parameters in an orderly manner I wish them to be respectively ?
For example, to enter parameters: 20,40,50,60,90

**Comment by hongyuanjia** [comment]
Hi @mdakyen. Sorry for the late reply.

In optimization, even though parameters are given in an orderly manner, the order will be ignored. Because the value of parameters is determined by the optimization algorithm itself. If you wish to use a certain sequential, maybe you can try to run a normal parametric simulation instead of going for optimization. Hope this helps.

**Comment by mdakyen** [comment]
Its Ok @hongyuanjia.
Thanks for the conformation of the optimization algorithm behavior towards parameters.
